### ISSUE TITLE
Outreachy Task 1 Progress

### ISSUE THREAD

**Issue by alswajiab** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#172]
### Task 1 : Subpages

*Your task is to create a single subpage for one of the following topics:*
- [ ] 1. OPEN SOURCE 
- [ ] 2. OPEN LICENSE
- [ ] 3. OPEN HARDWARE
- [ ] 4. FAIR PRINCIPLES → [Subpages for FAIR Principle #30 ](https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/30)
- [ ] 5. OPEN EDUCATIONAL RESOURCES
- [ ] 6. OPEN ACCESS

*Each subpage should include the following:*

- [ ] 1. A summary of the concept you choose from these sections (What is x (e.g. open access)? Where can I read about (e.g. open access)?
- [ ] 2. Illustration (image explaining the concept) with alternative tag - you can find any image online!
- [ ] 3. The video impeded in iframe.
- [ ] 4. Maintain the same header, footer and other colours and design from the original website.
- [ ] 5. Have a way to get back to the main page.
- [ ] 6. The same page is reflected in both the Arabic and English pages.
- [ ] 7. Open a Pull request with your changes and state in the PR how you can further improve the website.
 
**Notes**:
* So rather than directing the user to Youtube directly, the user will be directed to a new page on the website that has the video embedded and a summary about x.
* You don't need to know Arabic; there will be another intern who will be helping with Arabic. but use Google translate for the demo and submit a PR.

**Comment by JesperKawuma** [comment]
Thanks @alswajiab for this. Does this mean that part 6 is the available to work on?

**Comment by alswajiab** [comment]
> Thanks @alswajiab for this. Does this mean that part 6 is the available to work on?

Yes, @JesperKawudo, If you would like to take this part, Please open a new issue to let everyone know you are working on this part.

Good luck.

**Comment by RealRichi3** [comment]
@alswajiab i would like to work on task 6

**Comment by mildrette** [comment]
@alswajiab please assign me to part 6 (OPEN ACCESS) if no one is working on it, please

**Comment by JesperKawuma** [comment]
So @alswajiab, what this means is that one should research about **open access** then make a summary about the latter plus other relevant sources. Is this what you guys meant?

**Comment by alswajiab** [comment]
Thank you, @RealRichi3 and @mildrette, for your interest to contribute. We will go through the tasks and let you know if more tasks are available.

**Comment by JesperKawuma** [comment]
We are available, Sir.

**Comment by mildrette** [comment]
> Thank you, @RealRichi3 and @mildrette, for your interest in contributing. We will review the tasks and let you know if more tasks are available. Feel free to check other open PRs, especially if you couldn't work on any tasks yet.

okay thank you very much

**Comment by GuddyTech** [comment]
@RealRichi3 and @mildrette can I also collaborate with you guys to complete this task?

**Comment by okerekechinweotito** [comment]
@alswajiab  I can see that task 1.6 (OPEN ACCESS) has not been done.  I have created an issue for it here #177 and I have also made a PR for it here #178 .   Please Review and Link my PR to Task 6 above.  Thank you

**Comment by sandygudie** [comment]
@alswajiab i will take on task 3, i will open an issue on it

**Comment by jesutobi** [comment]
@alswajiab Goodmorning, can several persons work on one issue, because the task you listed here have been taken by other contributors,

**Comment by sandygudie** [comment]
@adetyaz  yeah sure

**Comment by adetyaz** [comment]
Thanks @sandygudie I'll work on Task 3.2

**Comment by adetyaz** [comment]
What of task 3.3

**Comment by adetyaz** [comment]
Okies,
on my own end what i'll do is do 3.2 in order to get to the 3.3 then when your's have been merged i can just pull then push 3.3.

It also depends on if you're making a pr for 3.2

**Comment by adetyaz** [comment]
Alright thanks I'll do the needful and push @sandygudie

**Comment by adetyaz** [comment]
I have made a pr for it with, the external links added #189

**Comment by okerekechinweotito** [comment]
@alswajiab  Task 3 (Events Subpages) has not been completed.  I have created an issue for it here #188 and I have also made a PR for it here #190.   Please Review and Link my PR to Task 3 above.  Thank you

**Comment by GuddyTech** [comment]
Please what time is the google meet @sandygudie

**Comment by Tammy-Ajoko** [comment]
please is this task still open

**Comment by Jolah1** [comment]
@BatoolMM please can i go ahead with task 2 now? seems people have worked on task 1 already.
Thank You

**Comment by JesperKawuma** [comment]
Hello @alswajiab is task one already done such that I find myself a new issue to work on
